/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof pay
* @enum {string}
*/
ErrorCode = {
  TERMINAL_BUSY : "TERMINAL_BUSY",
  TERMINAL_UNAVAILABLE : "TERMINAL_UNAVAILABLE",
  TERMINAL_GENERAL : "TERMINAL_GENERAL"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ErrorCode;
}

