/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* `CREATED`: The print event is created
* `FAILED`: The primary printing device failed to print
* `DONE`: The print event is sent to device and get printed
* @memberof order
* @enum {string}
*/
PrintState = {
  CREATED : "CREATED",
  FAILED : "FAILED",
  DONE : "DONE"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = PrintState;
}

