/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof payments
* @enum {string}
*/
AssociationType = {
  GOVT_ED_SERVICE_FEE : "GOVT_ED_SERVICE_FEE"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = AssociationType;
}

