/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var payments_BatchCardTotal = require("../payments/BatchCardTotal");
var payments_BatchTotalStats = require("../payments/BatchTotalStats");
var payments_ServerTotalStats = require("../payments/ServerTotalStats");

/**
* @constructor
* @memberof payments
*/
var BatchDetail = function() {
  this._class_ = BatchDetail;
  this.batchTotals = undefined;
  this.serverTotals = undefined;
  this.cardTotals = undefined;
  this.openTips = undefined;
  this.openTabs = undefined;
};


/**
* Set the field value
* @memberof payments.BatchDetail
* @param {payments.BatchTotalStats} batchTotals 
*/
BatchDetail.prototype.setBatchTotals = function(batchTotals) {
  this.batchTotals = batchTotals;
};

/**
* Get the field value
* @memberof payments.BatchDetail
* @return {payments.BatchTotalStats} 
*/
BatchDetail.prototype.getBatchTotals = function() {
  return this.batchTotals;
};

/**
* Set the field value
* @memberof payments.BatchDetail
* @param {Array.<payments.ServerTotalStats>} serverTotals An array of 
*/
BatchDetail.prototype.setServerTotals = function(serverTotals) {
  this.serverTotals = serverTotals;
};

/**
* Get the field value
* @memberof payments.BatchDetail
* @return {Array.<payments.ServerTotalStats>} An array of 
*/
BatchDetail.prototype.getServerTotals = function() {
  return this.serverTotals;
};

/**
* Set the field value
* @memberof payments.BatchDetail
* @param {Array.<payments.BatchCardTotal>} cardTotals An array of 
*/
BatchDetail.prototype.setCardTotals = function(cardTotals) {
  this.cardTotals = cardTotals;
};

/**
* Get the field value
* @memberof payments.BatchDetail
* @return {Array.<payments.BatchCardTotal>} An array of 
*/
BatchDetail.prototype.getCardTotals = function() {
  return this.cardTotals;
};

/**
* Set the field value
* Number of open tips.
*
* @memberof payments.BatchDetail
* @param {Number} openTips must be a long integer
*/
BatchDetail.prototype.setOpenTips = function(openTips) {
  this.openTips = openTips;
};

/**
* Get the field value
* Number of open tips.
* @memberof payments.BatchDetail
* @return {Number} must be a long integer
*/
BatchDetail.prototype.getOpenTips = function() {
  return this.openTips;
};

/**
* Set the field value
* Number of open tabs.
*
* @memberof payments.BatchDetail
* @param {Number} openTabs must be a long integer
*/
BatchDetail.prototype.setOpenTabs = function(openTabs) {
  this.openTabs = openTabs;
};

/**
* Get the field value
* Number of open tabs.
* @memberof payments.BatchDetail
* @return {Number} must be a long integer
*/
BatchDetail.prototype.getOpenTabs = function() {
  return this.openTabs;
};

/**
* @memberof payments.BatchDetail
* @private
*/
BatchDetail.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    if(curclass._meta_._superMeta_) {
      curclass = curclass._meta_._superMeta_._class_;
    } else {
      curclass = null;
    }
  } while(curclass);
  return null;
};

BatchDetail.prototype.toString = function() {
  return JSON.stringify(this);
};

BatchDetail._meta_ =  {fields:  {}};
BatchDetail._meta_._class_ =  BatchDetail;
BatchDetail._meta_.fields["batchTotals"] = {};
BatchDetail._meta_.fields["batchTotals"].type = payments_BatchTotalStats;
BatchDetail._meta_.fields["serverTotals"] = {};
BatchDetail._meta_.fields["serverTotals"].type = Array;
BatchDetail._meta_.fields["serverTotals"].elementType = payments_ServerTotalStats;
BatchDetail._meta_.fields["cardTotals"] = {};
BatchDetail._meta_.fields["cardTotals"].type = Array;
BatchDetail._meta_.fields["cardTotals"].elementType = payments_BatchCardTotal;
BatchDetail._meta_.fields["openTips"] = {};
BatchDetail._meta_.fields["openTips"].type = Number;
BatchDetail._meta_.fields["openTabs"] = {};
BatchDetail._meta_.fields["openTabs"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = BatchDetail;
}

