/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var payments_Payment = require("../payments/Payment");

/**
* @constructor
* @memberof payments
*/
var PaymentResponse = function() {
  this._class_ = PaymentResponse;
  this.requestSuccessful = undefined;
  this.responseErrorMessage = undefined;
  this.payment = undefined;
};


/**
* Set the field value
* @memberof payments.PaymentResponse
* @param {Boolean} requestSuccessful 
*/
PaymentResponse.prototype.setRequestSuccessful = function(requestSuccessful) {
  this.requestSuccessful = requestSuccessful;
};

/**
* Get the field value
* @memberof payments.PaymentResponse
* @return {Boolean} 
*/
PaymentResponse.prototype.getRequestSuccessful = function() {
  return this.requestSuccessful;
};

/**
* Set the field value
* @memberof payments.PaymentResponse
* @param {String|Null} responseErrorMessage 
*/
PaymentResponse.prototype.setResponseErrorMessage = function(responseErrorMessage) {
  this.responseErrorMessage = responseErrorMessage;
};

/**
* Get the field value
* @memberof payments.PaymentResponse
* @return {String|Null} 
*/
PaymentResponse.prototype.getResponseErrorMessage = function() {
  return this.responseErrorMessage;
};

/**
* Set the field value
* @memberof payments.PaymentResponse
* @param {payments.Payment|Null} payment 
*/
PaymentResponse.prototype.setPayment = function(payment) {
  this.payment = payment;
};

/**
* Get the field value
* @memberof payments.PaymentResponse
* @return {payments.Payment|Null} 
*/
PaymentResponse.prototype.getPayment = function() {
  return this.payment;
};

/**
* @memberof payments.PaymentResponse
* @private
*/
PaymentResponse.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    curclass = curclass.superclass;
  } while(curclass);
  return null;
};

PaymentResponse.prototype.toString = function() {
  return JSON.stringify(this);
};

PaymentResponse._meta_ =  {fields:  {}};
PaymentResponse._meta_.fields["requestSuccessful"] = {};
PaymentResponse._meta_.fields["requestSuccessful"].type = Boolean;
PaymentResponse._meta_.fields["responseErrorMessage"] = {};
PaymentResponse._meta_.fields["responseErrorMessage"].type = String;
PaymentResponse._meta_.fields["payment"] = {};
PaymentResponse._meta_.fields["payment"].type = payments_Payment;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = PaymentResponse;
}

