/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var payments_TerminalManagementComponentType = require("../payments/TerminalManagementComponentType");

/**
* @constructor
* @memberof payments
*/
var TerminalManagementComponent = function() {
  this._class_ = TerminalManagementComponent;
  this.type = undefined;
  this.itemNumber = undefined;
  this.provider = undefined;
  this.serial = undefined;
  this.version = undefined;
  this.identification = undefined;
};


/**
* Set the field value
* @memberof payments.TerminalManagementComponent
* @param {payments.TerminalManagementComponentType} type 
*/
TerminalManagementComponent.prototype.setType = function(type) {
  this.type = type;
};

/**
* Get the field value
* @memberof payments.TerminalManagementComponent
* @return {payments.TerminalManagementComponentType} 
*/
TerminalManagementComponent.prototype.getType = function() {
  return this.type;
};

/**
* Set the field value
* @memberof payments.TerminalManagementComponent
* @param {String} itemNumber 
*/
TerminalManagementComponent.prototype.setItemNumber = function(itemNumber) {
  this.itemNumber = itemNumber;
};

/**
* Get the field value
* @memberof payments.TerminalManagementComponent
* @return {String} 
*/
TerminalManagementComponent.prototype.getItemNumber = function() {
  return this.itemNumber;
};

/**
* Set the field value
* @memberof payments.TerminalManagementComponent
* @param {String} provider 
*/
TerminalManagementComponent.prototype.setProvider = function(provider) {
  this.provider = provider;
};

/**
* Get the field value
* @memberof payments.TerminalManagementComponent
* @return {String} 
*/
TerminalManagementComponent.prototype.getProvider = function() {
  return this.provider;
};

/**
* Set the field value
* @memberof payments.TerminalManagementComponent
* @param {String} serial 
*/
TerminalManagementComponent.prototype.setSerial = function(serial) {
  this.serial = serial;
};

/**
* Get the field value
* @memberof payments.TerminalManagementComponent
* @return {String} 
*/
TerminalManagementComponent.prototype.getSerial = function() {
  return this.serial;
};

/**
* Set the field value
* @memberof payments.TerminalManagementComponent
* @param {String} version 
*/
TerminalManagementComponent.prototype.setVersion = function(version) {
  this.version = version;
};

/**
* Get the field value
* @memberof payments.TerminalManagementComponent
* @return {String} 
*/
TerminalManagementComponent.prototype.getVersion = function() {
  return this.version;
};

/**
* Set the field value
* @memberof payments.TerminalManagementComponent
* @param {String} identification 
*/
TerminalManagementComponent.prototype.setIdentification = function(identification) {
  this.identification = identification;
};

/**
* Get the field value
* @memberof payments.TerminalManagementComponent
* @return {String} 
*/
TerminalManagementComponent.prototype.getIdentification = function() {
  return this.identification;
};

/**
* @memberof payments.TerminalManagementComponent
* @private
*/
TerminalManagementComponent.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    if(curclass._meta_._superMeta_) {
      curclass = curclass._meta_._superMeta_._class_;
    } else {
      curclass = null;
    }
  } while(curclass);
  return null;
};

TerminalManagementComponent.prototype.toString = function() {
  return JSON.stringify(this);
};

TerminalManagementComponent._meta_ =  {fields:  {}};
TerminalManagementComponent._meta_._class_ =  TerminalManagementComponent;
TerminalManagementComponent._meta_.fields["type"] = {};
TerminalManagementComponent._meta_.fields["type"].type = payments_TerminalManagementComponentType;
TerminalManagementComponent._meta_.fields["itemNumber"] = {};
TerminalManagementComponent._meta_.fields["itemNumber"].type = String;
TerminalManagementComponent._meta_.fields["provider"] = {};
TerminalManagementComponent._meta_.fields["provider"].type = String;
TerminalManagementComponent._meta_.fields["serial"] = {};
TerminalManagementComponent._meta_.fields["serial"].type = String;
TerminalManagementComponent._meta_.fields["version"] = {};
TerminalManagementComponent._meta_.fields["version"].type = String;
TerminalManagementComponent._meta_.fields["identification"] = {};
TerminalManagementComponent._meta_.fields["identification"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TerminalManagementComponent;
}

