/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var payments_TerminalManagementEvent = require("../payments/TerminalManagementEvent");
var payments_TerminalManagementPlanAction = require("../payments/TerminalManagementPlanAction");

/**
* @constructor
* @memberof payments
*/
var TerminalManagementPlan = function() {
  this._class_ = TerminalManagementPlan;
  this.name = undefined;
  this.source = undefined;
  this.createdTime = undefined;
  this.actions = undefined;
  this.events = undefined;
};


/**
* Set the field value
* @memberof payments.TerminalManagementPlan
* @param {String} name 
*/
TerminalManagementPlan.prototype.setName = function(name) {
  this.name = name;
};

/**
* Get the field value
* @memberof payments.TerminalManagementPlan
* @return {String} 
*/
TerminalManagementPlan.prototype.getName = function() {
  return this.name;
};

/**
* Set the field value
* id of the source of the plan
*
* @memberof payments.TerminalManagementPlan
* @param {String} source 
*/
TerminalManagementPlan.prototype.setSource = function(source) {
  this.source = source;
};

/**
* Get the field value
* id of the source of the plan
* @memberof payments.TerminalManagementPlan
* @return {String} 
*/
TerminalManagementPlan.prototype.getSource = function() {
  return this.source;
};

/**
* Set the field value
* epoch time for the creation of the plan
*
* @memberof payments.TerminalManagementPlan
* @param {Number} createdTime must be a long integer
*/
TerminalManagementPlan.prototype.setCreatedTime = function(createdTime) {
  this.createdTime = createdTime;
};

/**
* Get the field value
* epoch time for the creation of the plan
* @memberof payments.TerminalManagementPlan
* @return {Number} must be a long integer
*/
TerminalManagementPlan.prototype.getCreatedTime = function() {
  return this.createdTime;
};

/**
* Set the field value
* Container for terminal management plan data
*
* @memberof payments.TerminalManagementPlan
* @param {Array.<payments.TerminalManagementPlanAction>} actions An array of 
*/
TerminalManagementPlan.prototype.setActions = function(actions) {
  this.actions = actions;
};

/**
* Get the field value
* Container for terminal management plan data
* @memberof payments.TerminalManagementPlan
* @return {Array.<payments.TerminalManagementPlanAction>} An array of 
*/
TerminalManagementPlan.prototype.getActions = function() {
  return this.actions;
};

/**
* Set the field value
* @memberof payments.TerminalManagementPlan
* @param {Array.<payments.TerminalManagementEvent>} events An array of 
*/
TerminalManagementPlan.prototype.setEvents = function(events) {
  this.events = events;
};

/**
* Get the field value
* @memberof payments.TerminalManagementPlan
* @return {Array.<payments.TerminalManagementEvent>} An array of 
*/
TerminalManagementPlan.prototype.getEvents = function() {
  return this.events;
};

/**
* @memberof payments.TerminalManagementPlan
* @private
*/
TerminalManagementPlan.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    if(curclass._meta_._superMeta_) {
      curclass = curclass._meta_._superMeta_._class_;
    } else {
      curclass = null;
    }
  } while(curclass);
  return null;
};

TerminalManagementPlan.prototype.toString = function() {
  return JSON.stringify(this);
};

TerminalManagementPlan._meta_ =  {fields:  {}};
TerminalManagementPlan._meta_._class_ =  TerminalManagementPlan;
TerminalManagementPlan._meta_.fields["name"] = {};
TerminalManagementPlan._meta_.fields["name"].type = String;
TerminalManagementPlan._meta_.fields["source"] = {};
TerminalManagementPlan._meta_.fields["source"].type = String;
TerminalManagementPlan._meta_.fields["createdTime"] = {};
TerminalManagementPlan._meta_.fields["createdTime"].type = Number;
TerminalManagementPlan._meta_.fields["actions"] = {};
TerminalManagementPlan._meta_.fields["actions"].type = Array;
TerminalManagementPlan._meta_.fields["actions"].elementType = payments_TerminalManagementPlanAction;
TerminalManagementPlan._meta_.fields["events"] = {};
TerminalManagementPlan._meta_.fields["events"].type = Array;
TerminalManagementPlan._meta_.fields["events"].elementType = payments_TerminalManagementEvent;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TerminalManagementPlan;
}

