/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof payments
* @enum {string}
*/
var VasDataTypeType = {
  ALL : "ALL",
  LOYALTY : "LOYALTY",
  OFFER : "OFFER",
  GIFT_CARD : "GIFT_CARD",
  PRIVATE_LABEL_CARD : "PRIVATE_LABEL_CARD",
  CUSTOMER : "CUSTOMER",
  VAS_DATA : "VAS_DATA"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VasDataTypeType;
}

