/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof loyalty
* @enum {string}
*/
CustomerProvidedDataResponseType = {
  ACCEPTED : "ACCEPTED",
  PENDING : "PENDING"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CustomerProvidedDataResponseType;
}

