/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @constructor
* @memberof inventory
*/
var MenuBulkUpdate = function() {
  this._class_ = MenuBulkUpdate;
  this.enabled = undefined;
  this.uuids = undefined;
};


/**
* Set the field value
* Set value to the enabled column in menu item, layout, modifier, or modifier group table in the bulk update action
*
* @memberof inventory.MenuBulkUpdate
* @param {Boolean} enabled 
*/
MenuBulkUpdate.prototype.setEnabled = function(enabled) {
  this.enabled = enabled;
};

/**
* Get the field value
* Set value to the enabled column in menu item, layout, modifier, or modifier group table in the bulk update action
* @memberof inventory.MenuBulkUpdate
* @return {Boolean} 
*/
MenuBulkUpdate.prototype.getEnabled = function() {
  return this.enabled;
};

/**
* Set the field value
* @memberof inventory.MenuBulkUpdate
* @param {Array.<String>} uuids An array of 
*/
MenuBulkUpdate.prototype.setUuids = function(uuids) {
  this.uuids = uuids;
};

/**
* Get the field value
* @memberof inventory.MenuBulkUpdate
* @return {Array.<String>} An array of 
*/
MenuBulkUpdate.prototype.getUuids = function() {
  return this.uuids;
};

/**
* @memberof inventory.MenuBulkUpdate
* @private
*/
MenuBulkUpdate.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    if(curclass._meta_._superMeta_) {
      curclass = curclass._meta_._superMeta_._class_;
    } else {
      curclass = null;
    }
  } while(curclass);
  return null;
};

MenuBulkUpdate.prototype.toString = function() {
  return JSON.stringify(this);
};

MenuBulkUpdate._meta_ =  {fields:  {}};
MenuBulkUpdate._meta_._class_ =  MenuBulkUpdate;
MenuBulkUpdate._meta_.fields["enabled"] = {};
MenuBulkUpdate._meta_.fields["enabled"].type = Boolean;
MenuBulkUpdate._meta_.fields["uuids"] = {};
MenuBulkUpdate._meta_.fields["uuids"].type = Array;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = MenuBulkUpdate;
}

