/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_ResultStatus = require("../remotemessage/ResultStatus");
var remotemessage_Message = require("../remotemessage/Message");
var base_CardData = require("../base/CardData");

/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var CardDataResponseMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = CardDataResponseMessage;
  this.setMethod(remotemessage_Method["CARD_DATA_RESPONSE"]);
  this.reason = undefined;
  this.status = undefined;
  this.cardData = undefined;
};

CardDataResponseMessage.prototype = Object.create(remotemessage_Message.prototype);
CardDataResponseMessage.prototype.constructor = CardDataResponseMessage;

/**
* Set the field value
* May be populated when the operation fails.
*
* @memberof remotemessage.CardDataResponseMessage
* @param {String} reason 
*/
CardDataResponseMessage.prototype.setReason = function(reason) {
  this.reason = reason;
};

/**
* Get the field value
* May be populated when the operation fails.
* @memberof remotemessage.CardDataResponseMessage
* @return {String} 
*/
CardDataResponseMessage.prototype.getReason = function() {
  return this.reason;
};

/**
* Set the field value
* @memberof remotemessage.CardDataResponseMessage
* @param {remotemessage.ResultStatus} status 
*/
CardDataResponseMessage.prototype.setStatus = function(status) {
  this.status = status;
};

/**
* Get the field value
* @memberof remotemessage.CardDataResponseMessage
* @return {remotemessage.ResultStatus} 
*/
CardDataResponseMessage.prototype.getStatus = function() {
  return this.status;
};

/**
* Set the field value
* The data for the card
*
* @memberof remotemessage.CardDataResponseMessage
* @param {base.CardData} cardData 
*/
CardDataResponseMessage.prototype.setCardData = function(cardData) {
  this.cardData = cardData;
};

/**
* Get the field value
* The data for the card
* @memberof remotemessage.CardDataResponseMessage
* @return {base.CardData} 
*/
CardDataResponseMessage.prototype.getCardData = function() {
  return this.cardData;
};

CardDataResponseMessage._meta_ =  {fields:  {}};
CardDataResponseMessage._meta_.fields["reason"] = {};
CardDataResponseMessage._meta_.fields["reason"].type = String;
CardDataResponseMessage._meta_.fields["status"] = {};
CardDataResponseMessage._meta_.fields["status"].type = remotemessage_ResultStatus;
CardDataResponseMessage._meta_.fields["cardData"] = {};
CardDataResponseMessage._meta_.fields["cardData"].type = base_CardData;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = CardDataResponseMessage;
}

