/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var IncrementPreAuthMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = IncrementPreAuthMessage;
  this.setMethod(remotemessage_Method["INCREMENT_PREAUTH_REQUEST"]);
  this.amount = undefined;
  this.paymentId = undefined;
};

IncrementPreAuthMessage.prototype = Object.create(remotemessage_Message.prototype);
IncrementPreAuthMessage.prototype.constructor = IncrementPreAuthMessage;

/**
* Set the field value
* The amount by which to increment the pre-auth.
*
* @memberof remotemessage.IncrementPreAuthMessage
* @param {Number} amount must be a long integer
*/
IncrementPreAuthMessage.prototype.setAmount = function(amount) {
  this.amount = amount;
};

/**
* Get the field value
* The amount by which to increment the pre-auth.
* @memberof remotemessage.IncrementPreAuthMessage
* @return {Number} must be a long integer
*/
IncrementPreAuthMessage.prototype.getAmount = function() {
  return this.amount;
};

/**
* Set the field value
* paymentId of the pre-auth to be incremented.
*
* @memberof remotemessage.IncrementPreAuthMessage
* @param {String} paymentId 
*/
IncrementPreAuthMessage.prototype.setPaymentId = function(paymentId) {
  this.paymentId = paymentId;
};

/**
* Get the field value
* paymentId of the pre-auth to be incremented.
* @memberof remotemessage.IncrementPreAuthMessage
* @return {String} 
*/
IncrementPreAuthMessage.prototype.getPaymentId = function() {
  return this.paymentId;
};

IncrementPreAuthMessage._meta_ =  {fields:  {}};
IncrementPreAuthMessage._meta_._class_ =  IncrementPreAuthMessage;
IncrementPreAuthMessage._meta_._superMeta_ = remotemessage_Message._meta_;
IncrementPreAuthMessage._meta_.fields["amount"] = {};
IncrementPreAuthMessage._meta_.fields["amount"].type = Number;
IncrementPreAuthMessage._meta_.fields["paymentId"] = {};
IncrementPreAuthMessage._meta_.fields["paymentId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = IncrementPreAuthMessage;
}

