/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @constructor
* @memberof remotemessage
*/
var OrderActionResponse = function() {
  this._class_ = OrderActionResponse;
  this.accepted = undefined;
  this.id = undefined;
};


/**
* Set the field value
* @memberof remotemessage.OrderActionResponse
* @param {Boolean} accepted 
*/
OrderActionResponse.prototype.setAccepted = function(accepted) {
  this.accepted = accepted;
};

/**
* Get the field value
* @memberof remotemessage.OrderActionResponse
* @return {Boolean} 
*/
OrderActionResponse.prototype.getAccepted = function() {
  return this.accepted;
};

/**
* Set the field value
* @memberof remotemessage.OrderActionResponse
* @param {String} id 
*/
OrderActionResponse.prototype.setId = function(id) {
  this.id = id;
};

/**
* Get the field value
* @memberof remotemessage.OrderActionResponse
* @return {String} 
*/
OrderActionResponse.prototype.getId = function() {
  return this.id;
};

/**
* @memberof remotemessage.OrderActionResponse
* @private
*/
OrderActionResponse.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    if(curclass._meta_._superMeta_) {
      curclass = curclass._meta_._superMeta_._class_;
    } else {
      curclass = null;
    }
  } while(curclass);
  return null;
};

OrderActionResponse.prototype.toString = function() {
  return JSON.stringify(this);
};

OrderActionResponse._meta_ =  {fields:  {}};
OrderActionResponse._meta_._class_ =  OrderActionResponse;
OrderActionResponse._meta_.fields["accepted"] = {};
OrderActionResponse._meta_.fields["accepted"].type = Boolean;
OrderActionResponse._meta_.fields["id"] = {};
OrderActionResponse._meta_.fields["id"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = OrderActionResponse;
}

