/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var order_VoidReason = require("../order/VoidReason");
var remotemessage_Message = require("../remotemessage/Message");
var payments_Payment = require("../payments/Payment");

/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var PaymentVoidedMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = PaymentVoidedMessage;
  this.setMethod(remotemessage_Method["PAYMENT_VOIDED"]);
  this.payment = undefined;
  this.voidReason = undefined;
};

PaymentVoidedMessage.prototype = Object.create(remotemessage_Message.prototype);
PaymentVoidedMessage.prototype.constructor = PaymentVoidedMessage;

/**
* Set the field value
* A payment
*
* @memberof remotemessage.PaymentVoidedMessage
* @param {payments.Payment} payment 
*/
PaymentVoidedMessage.prototype.setPayment = function(payment) {
  this.payment = payment;
};

/**
* Get the field value
* A payment
* @memberof remotemessage.PaymentVoidedMessage
* @return {payments.Payment} 
*/
PaymentVoidedMessage.prototype.getPayment = function() {
  return this.payment;
};

/**
* Set the field value
* @memberof remotemessage.PaymentVoidedMessage
* @param {order.VoidReason} voidReason 
*/
PaymentVoidedMessage.prototype.setVoidReason = function(voidReason) {
  this.voidReason = voidReason;
};

/**
* Get the field value
* @memberof remotemessage.PaymentVoidedMessage
* @return {order.VoidReason} 
*/
PaymentVoidedMessage.prototype.getVoidReason = function() {
  return this.voidReason;
};

PaymentVoidedMessage._meta_ =  {fields:  {}};
PaymentVoidedMessage._meta_.fields["payment"] = {};
PaymentVoidedMessage._meta_.fields["payment"].type = payments_Payment;
PaymentVoidedMessage._meta_.fields["voidReason"] = {};
PaymentVoidedMessage._meta_.fields["voidReason"].type = order_VoidReason;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = PaymentVoidedMessage;
}

