/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

/** Request to retrieve a payment made to a specific device. */
/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var RetrievePaymentRequestMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = RetrievePaymentRequestMessage;
  this.setMethod(remotemessage_Method["RETRIEVE_PAYMENT_REQUEST"]);
  this.externalPaymentId = undefined;
};

RetrievePaymentRequestMessage.prototype = Object.create(remotemessage_Message.prototype);
RetrievePaymentRequestMessage.prototype.constructor = RetrievePaymentRequestMessage;

/**
* Set the field value
* The externalPaymentId used when a payment was created
*
* @memberof remotemessage.RetrievePaymentRequestMessage
* @param {String} externalPaymentId 
*/
RetrievePaymentRequestMessage.prototype.setExternalPaymentId = function(externalPaymentId) {
  this.externalPaymentId = externalPaymentId;
};

/**
* Get the field value
* The externalPaymentId used when a payment was created
* @memberof remotemessage.RetrievePaymentRequestMessage
* @return {String} 
*/
RetrievePaymentRequestMessage.prototype.getExternalPaymentId = function() {
  return this.externalPaymentId;
};

RetrievePaymentRequestMessage._meta_ =  {fields:  {}};
RetrievePaymentRequestMessage._meta_._class_ =  RetrievePaymentRequestMessage;
RetrievePaymentRequestMessage._meta_._superMeta_ = remotemessage_Message._meta_;
RetrievePaymentRequestMessage._meta_.fields["externalPaymentId"] = {};
RetrievePaymentRequestMessage._meta_.fields["externalPaymentId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = RetrievePaymentRequestMessage;
}

