/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var TextPrintMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = TextPrintMessage;
  this.setMethod(remotemessage_Method["PRINT_TEXT"]);
  this.textLines = undefined;
};

TextPrintMessage.prototype = Object.create(remotemessage_Message.prototype);
TextPrintMessage.prototype.constructor = TextPrintMessage;

/**
* Set the field value
* @memberof remotemessage.TextPrintMessage
* @param {Array.<String>} textLines An array of 
*/
TextPrintMessage.prototype.setTextLines = function(textLines) {
  this.textLines = textLines;
};

/**
* Get the field value
* @memberof remotemessage.TextPrintMessage
* @return {Array.<String>} An array of 
*/
TextPrintMessage.prototype.getTextLines = function() {
  return this.textLines;
};

TextPrintMessage._meta_ =  {fields:  {}};
TextPrintMessage._meta_.fields["textLines"] = {};
TextPrintMessage._meta_.fields["textLines"].type = Array;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = TextPrintMessage;
}

