/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var payments_VasMode = require("../payments/VasMode");
var remotemessage_Message = require("../remotemessage/Message");
var payments_VasPayload = require("../payments/VasPayload");

/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var VasPayloadMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = VasPayloadMessage;
  this.setMethod(remotemessage_Method["VAS_PAYLOAD_MESSAGE"]);
  this.vasPayload = undefined;
  this.vasMode = undefined;
};

VasPayloadMessage.prototype = Object.create(remotemessage_Message.prototype);
VasPayloadMessage.prototype.constructor = VasPayloadMessage;

/**
* Set the field value
* A VAS payload
*
* @memberof remotemessage.VasPayloadMessage
* @param {payments.VasPayload} vasPayload 
*/
VasPayloadMessage.prototype.setVasPayload = function(vasPayload) {
  this.vasPayload = vasPayload;
};

/**
* Get the field value
* A VAS payload
* @memberof remotemessage.VasPayloadMessage
* @return {payments.VasPayload} 
*/
VasPayloadMessage.prototype.getVasPayload = function() {
  return this.vasPayload;
};

/**
* Set the field value
* The VAS mode for the payload
*
* @memberof remotemessage.VasPayloadMessage
* @param {payments.VasMode} vasMode 
*/
VasPayloadMessage.prototype.setVasMode = function(vasMode) {
  this.vasMode = vasMode;
};

/**
* Get the field value
* The VAS mode for the payload
* @memberof remotemessage.VasPayloadMessage
* @return {payments.VasMode} 
*/
VasPayloadMessage.prototype.getVasMode = function() {
  return this.vasMode;
};

VasPayloadMessage._meta_ =  {fields:  {}};
VasPayloadMessage._meta_._class_ =  VasPayloadMessage;
VasPayloadMessage._meta_._superMeta_ = remotemessage_Message._meta_;
VasPayloadMessage._meta_.fields["vasPayload"] = {};
VasPayloadMessage._meta_.fields["vasPayload"].type = payments_VasPayload;
VasPayloadMessage._meta_.fields["vasMode"] = {};
VasPayloadMessage._meta_.fields["vasMode"].type = payments_VasMode;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VasPayloadMessage;
}

