/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotemessage_Method = require("../remotemessage/Method");
var remotemessage_Message = require("../remotemessage/Message");

/**
* @constructor
* @augments remotemessage.Message
* @memberof remotemessage
*/
var VaultCardMessage = function() {
  remotemessage_Message.call(this);
  this._superClass_ = remotemessage_Message;
  this._class_ = VaultCardMessage;
  this.setMethod(remotemessage_Method["VAULT_CARD"]);
  this.cardEntryMethods = undefined;
};

VaultCardMessage.prototype = Object.create(remotemessage_Message.prototype);
VaultCardMessage.prototype.constructor = VaultCardMessage;

/**
* Set the field value
* Allowed entry methods
*
* @memberof remotemessage.VaultCardMessage
* @param {Number} cardEntryMethods must be an integer
*/
VaultCardMessage.prototype.setCardEntryMethods = function(cardEntryMethods) {
  this.cardEntryMethods = cardEntryMethods;
};

/**
* Get the field value
* Allowed entry methods
* @memberof remotemessage.VaultCardMessage
* @return {Number} must be an integer
*/
VaultCardMessage.prototype.getCardEntryMethods = function() {
  return this.cardEntryMethods;
};

VaultCardMessage._meta_ =  {fields:  {}};
VaultCardMessage._meta_.fields["cardEntryMethods"] = {};
VaultCardMessage._meta_.fields["cardEntryMethods"].type = Number;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = VaultCardMessage;
}

