/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @memberof device
* @enum {string}
*/
var DeviceAccessoryBuildType = {
  ENG : "ENG",
  USER : "USER",
  USERDEBUG : "USERDEBUG"
};


//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = DeviceAccessoryBuildType;
}

