/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


/**
* @constructor
* @memberof order.operation
*/
var DiscountsDeletedOperation = function() {
  this._class_ = DiscountsDeletedOperation;
  this.ids = undefined;
  this.orderId = undefined;
};


/**
* Set the field value
* @memberof order.operation.DiscountsDeletedOperation
* @param {Array.<String>} ids An array of 
*/
DiscountsDeletedOperation.prototype.setIds = function(ids) {
  this.ids = ids;
};

/**
* Get the field value
* @memberof order.operation.DiscountsDeletedOperation
* @return {Array.<String>} An array of 
*/
DiscountsDeletedOperation.prototype.getIds = function() {
  return this.ids;
};

/**
* Set the field value
* @memberof order.operation.DiscountsDeletedOperation
* @param {String} orderId 
*/
DiscountsDeletedOperation.prototype.setOrderId = function(orderId) {
  this.orderId = orderId;
};

/**
* Get the field value
* @memberof order.operation.DiscountsDeletedOperation
* @return {String} 
*/
DiscountsDeletedOperation.prototype.getOrderId = function() {
  return this.orderId;
};

/**
* @memberof order.operation.DiscountsDeletedOperation
* @private
*/
DiscountsDeletedOperation.prototype.getMetaInfo = function(fieldName) {
  var curclass = this._class_;
  do {
    var fieldMetaInfo = curclass._meta_.fields[fieldName];
    if(fieldMetaInfo) {
      return fieldMetaInfo;
    }
    if(curclass._meta_._superMeta_) {
      curclass = curclass._meta_._superMeta_._class_;
    } else {
      curclass = null;
    }
  } while(curclass);
  return null;
};

DiscountsDeletedOperation.prototype.toString = function() {
  return JSON.stringify(this);
};

DiscountsDeletedOperation._meta_ =  {fields:  {}};
DiscountsDeletedOperation._meta_._class_ =  DiscountsDeletedOperation;
DiscountsDeletedOperation._meta_.fields["ids"] = {};
DiscountsDeletedOperation._meta_.fields["ids"].type = Array;
DiscountsDeletedOperation._meta_.fields["orderId"] = {};
DiscountsDeletedOperation._meta_.fields["orderId"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = DiscountsDeletedOperation;
}

