/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotepay_BaseRequest = require("../remotepay/BaseRequest");

/** A message used in custom activities */
/**
* @constructor
* @augments remotepay.BaseRequest
* @memberof remotepay
*/
var ActivityMessage = function() {
  remotepay_BaseRequest.call(this);
  this._superClass_ = remotepay_BaseRequest;
  this._class_ = ActivityMessage;
  this.action = undefined;
  this.payload = undefined;
};

ActivityMessage.prototype = Object.create(remotepay_BaseRequest.prototype);
ActivityMessage.prototype.constructor = ActivityMessage;

/**
* Set the field value
* An action name, such as ACTION_VIEW.  Application-specific actions should be prefixed with the vendor's package name.
*
* @memberof remotepay.ActivityMessage
* @param {String} action 
*/
ActivityMessage.prototype.setAction = function(action) {
  this.action = action;
};

/**
* Get the field value
* An action name, such as ACTION_VIEW.  Application-specific actions should be prefixed with the vendor's package name.
* @memberof remotepay.ActivityMessage
* @return {String} 
*/
ActivityMessage.prototype.getAction = function() {
  return this.action;
};

/**
* Set the field value
* Information that is passed to the activity.  Can be obtained from the intent using the key defined in com.clover.remote.common.RemoteConstants#EXTRA_PAYLOAD
*
* @memberof remotepay.ActivityMessage
* @param {String|Null} payload 
*/
ActivityMessage.prototype.setPayload = function(payload) {
  this.payload = payload;
};

/**
* Get the field value
* Information that is passed to the activity.  Can be obtained from the intent using the key defined in com.clover.remote.common.RemoteConstants#EXTRA_PAYLOAD
* @memberof remotepay.ActivityMessage
* @return {String|Null} 
*/
ActivityMessage.prototype.getPayload = function() {
  return this.payload;
};

ActivityMessage._meta_ =  {fields:  {}};
ActivityMessage._meta_._class_ =  ActivityMessage;
ActivityMessage._meta_._superMeta_ = remotepay_BaseRequest._meta_;
ActivityMessage._meta_.fields["action"] = {};
ActivityMessage._meta_.fields["action"].type = String;
ActivityMessage._meta_.fields["payload"] = {};
ActivityMessage._meta_.fields["payload"].type = String;

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = ActivityMessage;
}

