/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

var remotepay_TransactionType = require("../remotepay/TransactionType");
var remotepay_TransactionRequest = require("../remotepay/TransactionRequest");

/**
* @constructor
* @augments remotepay.TransactionRequest
* @memberof remotepay
*/
var PreAuthRequest = function() {
  remotepay_TransactionRequest.call(this);
  this._superClass_ = remotepay_TransactionRequest;
  this._class_ = PreAuthRequest;
  this.setType(remotepay_TransactionType["AUTH"]);
};

PreAuthRequest.prototype = Object.create(remotepay_TransactionRequest.prototype);
PreAuthRequest.prototype.constructor = PreAuthRequest;

PreAuthRequest._meta_ =  {fields:  {}};

//
// Expose the module.
//
if ('undefined' !== typeof module) {
module.exports = PreAuthRequest;
}

